### ISSUE TITLE
The GetQueue operation fails

### ISSUE THREAD

**Issue by SkullTech** [aertje/cloud-tasks-emulator#38]
Here's how one can reproduce the bug

```console
$ docker run -p 8123:8123 ghcr.io/aertje/cloud-tasks-emulator:latest -host 0.0.0.0 -port 8123 
```

```python
import grpc
from google.cloud.tasks_v2 import CloudTasksClient
from google.cloud.tasks_v2.services.cloud_tasks.transports import CloudTasksGrpcTransport

channel = grpc.insecure_channel('localhost:8123')
transport = CloudTasksGrpcTransport(channel=channel)
client = CloudTasksClient(transport=transport)

queue_path = client.queue_path('my-sandbox', 'us-central1', 'my-queue')
client.get_queue(name=queue_path)
```

This is the error log
```
Starting cloud tasks emulator, listening on 0.0.0.0:8123
Creating initial queue /projects/my-sandbox/locations/us-central1/queues/test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8681bb]

goroutine 1042 [running]:
main.(*Server).GetQueue(0xc00000ef20, 0xa5dac0, 0xc00047e1e0, 0xc00047e210, 0xc00000ef20, 0xc00047e1e0, 0xc0001d3a80)
	/app/emulator.go:100 +0x4b
google.golang.org/genproto/googleapis/cloud/tasks/v2._CloudTasks_GetQueue_Handler(0x982420, 0xc00000ef20, 0xa5dac0, 0xc00047e1e0, 0xc00037b620, 0x0, 0xa5dac0, 0xc00047e1e0, 0xc0004940c0, 0x3b)
	/go/pkg/mod/google.golang.org/genproto@v0.0.0-20191115221424-83cc0476cb11/googleapis/cloud/tasks/v2/cloudtasks.pb.go:1603 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001980, 0xa62520, 0xc000142900, 0xc00049c000, 0xc0000f2d50, 0xdd0858, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc000001980, 0xa62520, 0xc000142900, 0xc00049c000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000294e0, 0xc000001980, 0xa62520, 0xc000142900, 0xc00049c000)
	/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1
```

**Comment by SkullTech** [comment]
This happens even if the queue already exists.

**Comment by aertje** [comment]
Thanks for reporting @SkullTech; that whole method is basically still one big [TODO](https://github.com/aertje/cloud-tasks-emulator/blob/37639f660876d8f816fc2e2b7d31db74e40b6b25/emulator.go#L98) although it surprises me it doesn't work if the queue already exists.

**Comment by SkullTech** [comment]
Okay I checked again and you're right, it does work when the queue already exists.
