### ISSUE TITLE
 SIGSEGV: segmentation violation memory error when creating a task

### ISSUE THREAD

**Issue by edufresne** [aertje/cloud-tasks-emulator#55]
The cloud tasks emulator was working great but I started running into memory access errors when running the most recent docker image if the code I was using had large amounts of tasks.

I have an endpoint that is executed by cloud tasks that then acts as a dispatcher for multiple other tasks. The docker container then crashes once they start getting created.

Logs:
```
Starting cloud tasks emulator, listening on 0.0.0.0:8123
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x71d83f]

goroutine 57 [running]:
net/http.(*Client).do(0xc000508690, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:518 +0x5f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:509
main.dispatch(0xc000532001, 0xc000532000, 0x0)
        /app/task.go:353 +0x87a
main.(*Task).doDispatch(0xc00050e100, 0xc000532101)
        /app/task.go:364 +0x38
main.(*Task).Attempt(0xc00050e100)
        /app/task.go:374 +0x3e
main.(*Queue).runWorker(0xc000184d20)
        /app/queue.go:127 +0x3f
created by main.(*Queue).runWorkers
        /app/queue.go:119 +0x48
```

Code
```python
import uuid

import grpc
from google.cloud.tasks_v2 import CloudTasksClient, HttpRequest, Queue, Task
from google.cloud.tasks_v2.services.cloud_tasks.transports import CloudTasksGrpcTransport

channel = grpc.insecure_channel('localhost:8123')

transport = CloudTasksGrpcTransport(channel=channel)

client = CloudTasksClient(transport=transport)

parent = 'projects/my-sandbox/locations/us-central1'
queue_name = parent + f'/queues/{uuid.uuid4()}'


client.create_queue(queue=Queue({'name': queue_name}), parent=parent)


task = client.create_task(task=Task(http_request=HttpRequest(url='http://host.docker.internal:5000/v1')), parent=queue_name) # 200
```

**Comment by aertje** [comment]
Thanks for reporting! Am I right in saying this issue only occurred for you in the latest docker image? What version were you using before where this did not occur?

**Comment by edufresne** [comment]
Sorry, I actually haven't used any of the past images, but I can give it a shot with an older version and see if it still pops up.

**Comment by edufresne** [comment]
@aertje Bumped down to an old version and was still able to reproduce the same issue. Also I was able to reproduce this without any concurrency from just running the script above^ in my console.

**Comment by aertje** [comment]
Can you paste a snippet of what is executed when the task hits http://host.docker.internal:5000/v1 ?

**Comment by edufresne** [comment]
It's a Python Flask app that just simply returns a `204 No Content` response
```python
from flask import Blueprint


heartbeat_endpoints = Blueprint("base_v1", __name__)


@heartbeat_endpoints.route("/", strict_slashes=False, methods=["GET"])
def hello():
    return "", 204
```

**Comment by aertje** [comment]
I was expecting to see the dispatching for multiple other tasks to happen on this endpoint, as per your original comment. 
Another thing I noticed is that the default Task method is a POST, whereas your handler only handles GET. 

I'm not suggesting this is the cause of the issue but does make me wonder whether we're looking at the right thing to try to understand what is happening. The only specific thing about your use case I can see is that it could trigger some kind of exponential / avalanche behaviour, which is why I want to understand the _"an endpoint that is executed by cloud tasks that then acts as a dispatcher for multiple other tasks"_ bit.

**Comment by molloyjj** [comment]
Running into this issue when creating a single task using the node.js cloud-tasks library. Publishing a task with the GET verb to a GET endpoint in a similar manner to the above. any update on this? 

Error logs:
```
cloud-run-gcloud-tasks-emulator-1  | panic: runtime error: invalid memory address or nil pointer dereference
cloud-run-gcloud-tasks-emulator-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x868bd3]
cloud-run-gcloud-tasks-emulator-1  | 
cloud-run-gcloud-tasks-emulator-1  | goroutine 43 [running]:
cloud-run-gcloud-tasks-emulator-1  | sync.(*Mutex).Lock(...)
cloud-run-gcloud-tasks-emulator-1  |    /usr/local/go/src/sync/mutex.go:74
cloud-run-gcloud-tasks-emulator-1  | main.(*Server).ListTasks(0xc00000ef20, 0xa5dcc0, 0xc0001b88d0, 0xc0001da3c0, 0x0, 0x0, 0x0)
cloud-run-gcloud-tasks-emulator-1  |    /app/emulator.go:210 +0x93
cloud-run-gcloud-tasks-emulator-1  | google.golang.org/genproto/googleapis/cloud/tasks/v2._CloudTasks_ListTasks_Handler(0x982420, 0xc00000ef20, 0xa5dcc0, 0xc0001b88d0, 0xc0004b93e0, 0x0, 0xa5dcc0, 0xc0001b88d0, 0x0, 0x0)
cloud-run-gcloud-tasks-emulator-1  |    /go/pkg/mod/google.golang.org/genproto@v0.0.0-20191115221424-83cc0476cb11/googleapis/cloud/tasks/v2/cloudtasks.pb.go:1783 +0x217
cloud-run-gcloud-tasks-emulator-1  | google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001980, 0xa62720, 0xc000082480, 0xc000578200, 0xc000100d50, 0xdd1948, 0x0, 0x0, 0x0)
cloud-run-gcloud-tasks-emulator-1  |    /go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x460
cloud-run-gcloud-tasks-emulator-1  | google.golang.org/grpc.(*Server).handleStream(0xc000001980, 0xa62720, 0xc000082480, 0xc000578200, 0x0)
cloud-run-gcloud-tasks-emulator-1  |    /go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd97
cloud-run-gcloud-tasks-emulator-1  | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000029150, 0xc000001980, 0xa62720, 0xc000082480, 0xc000578200)
cloud-run-gcloud-tasks-emulator-1  |    /go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xbb
cloud-run-gcloud-tasks-emulator-1  | created by google.golang.org/grpc.(*Server).serveStreams.func1
cloud-run-gcloud-tasks-emulator-1  |    /go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1
```
Create task code
```
    const parent = client.queuePath(project, location, queueName)
    await client.createTask({
        parent: parent,
        task: { httpRequest: { httpMethod: HttpMethod.GET, url: 'http://host.docker.internal:8080/ping' } },
    })
```
Endpoint is :
```
export const pingHandler = (_: Request, res: Response): void => {
    res.send('pong')
}
app = express()
app.get('/ping', pingHandler)
```

**Comment by aertje** [comment]
Thanks for reporting that @molloyjj; I found that can occur when the queue is deleted and the ListTasks method is subsequently called for the queue. I've addressed that in #74.

**Comment by molloyjj** [comment]
Thanks @aertje appreciate it!

**Comment by aertje** [comment]
Can you let me know if this resolved your occurrences of this issue @molloyjj ?

**Comment by aertje** [comment]
Since I haven't heard any more reports of this occurring, I will close this issue.

**Comment by HarithJ** [comment]
Hello @aertje,

I was facing the same issue, and the error, for me, had to do with the URL;

This did not work as I am missing a forward slash
```
endpoint="accountings/make_bulk_transfer/"
```

This one worked
```
endpoint="/accountings/make_bulk_transfer/"
```

But the error is really weird
